//
// Created by Urban on 11.04.2020.
//

#ifndef BOOSTTEST_SRC_BUILDER_BUILDERPATTERN_H_
#define BOOSTTEST_SRC_BUILDER_BUILDERPATTERN_H_

class BuilderPattern
{

};

#endif //BOOSTTEST_SRC_BUILDER_BUILDERPATTERN_H_
