//
// Created by Urban on 11.04.2020.
//

#ifndef BOOSTTEST_SRC_BUILDER_BUILDER_PATTERN_H_
#define BOOSTTEST_SRC_BUILDER_BUILDER_PATTERN_H_

class builder_pattern
{

};

#endif //BOOSTTEST_SRC_BUILDER_BUILDER_PATTERN_H_
