//
// Created by Urban on 12.04.2020.
//

#ifndef BOOSTTEST_SRC_BUILDER_GROOVYBUILDERPATTERN_H_
#define BOOSTTEST_SRC_BUILDER_GROOVYBUILDERPATTERN_H_

class GroovyBuilderPattern
{

};

#endif //BOOSTTEST_SRC_BUILDER_GROOVYBUILDERPATTERN_H_
