//
// Created by Urban on 12.04.2020.
//

#ifndef BOOSTTEST_SRC_BUILDER_GROOVY_BUILDER_PATTERN_H_
#define BOOSTTEST_SRC_BUILDER_GROOVY_BUILDER_PATTERN_H_

class groovy_builder_pattern
{

};

#endif //BOOSTTEST_SRC_BUILDER_GROOVY_BUILDER_PATTERN_H_
